### PR TITLE
1.1.3 update

### PR DESCRIPTION
**Pull request by joemerlino**
hope it works ;)

### CODE REVIEW

**Comment by tyhoff** [comment]
@joemerlino Have you tested this?

**Comment by joemerlino** [comment]
@tyhoff yes, i made a lighter version without the applist integration and with that override it works just fine. 
I'm overriding the method that produces the nil key causing the crash of the BTLEServer.
If you want i can test your version with applist even though i don't like to turn off all the switches for every app i have, because i want to suppress all the notifications.
If you don't have the enviroment installed i can give you a compiled .deb file so you can test it too.
P.S. love the new Pebble Time Steel ;) amazing product even though i can't afford it, i'll keep my original one :smile:

**Comment by joemerlino** [comment]
Hi! i updated again with some additions, published on my own repo and tested. Also tested by other people on [reddit/r/jailbreak](http://www.reddit.com/r/jailbreak/comments/2y07qm/fixed_pebbleprofiles_for_ios_8x/) and [reddit/r/pebble](http://www.reddit.com/r/pebble/comments/2y06sp/ios_fixed_version_of_pebbleprofiles_for_ios_8x/). It seems to work great.

**Comment by tyhoff** [comment]
Feel free to take ownership of the project. I would suggest keeping the "com.tyhoff.pebbleprofiles" since that will allow the users to be automatically updated, but you should be the one pushing to the bigboss repo. If you have any questions about that, let me know and I can help.

**Comment by joemerlino** [comment]
Thank you so much! I submitted this update to bigboss keeping the "com.tyhoff.pebbleprofiles", let's see if it will go live in 24 hours.

**Pull request merged**
